name: Create Sub-Repo Branches
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch name to create in all sub-repos'
        required: true

jobs:
  list-repos:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set repo matrix
        id: set-matrix
        # Test with a single repo first
        run: echo '::set-output name=matrix::["square1-wp-downloader"]'
        # TODO: replace the test with the full repo list
        # run: echo "::set-output name=matrix::$(php ./dev/monorepo/scripts/repo-list.php)"

  create-sub-repo-branches:
    needs: list-repos
    runs-on: ubuntu-latest
    env:
      org: 'moderntribe'
    strategy:
      matrix:
        repo-name: ${{ fromJson(needs.list-repos.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get commits
        uses: octokit/request-action@v2.x
        id: commits
        with:
          route: GET /repos/{owner}/{repo}/commits
          owner: ${{ env.org }}
          repo: ${{ matrix.repo-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get last SHA
        id: last-commit
        run: echo "::set-output name=sha::$( echo '${{ steps.commits.outputs.data }}' | jq -r .[0].sha)"

      - name: Create branch
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/git/refs
          owner: ${{ env.org }}
          repo: ${{ matrix.repo-name }}
          ref: "refs/heads/${{ github.event.inputs.branch }}"
          sha: "${{ steps.last-commit.outputs.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


